<?php

namespace Sphp\Core\Types;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-12 at 02:27:55.
 */
class ArraysTest extends \PHPUnit_Framework_TestCase {

  public function diffData() {
    return [
        [
            ["a" => "a", [1, 3 => 2], 4 => "f"],
            ["a" => "a", [1, 3 => 2], 4 => "f"],
            []
        ],
        [
            ["a" => new \stdClass],
            ["b" => new \stdClass],
            ["a" => new \stdClass]
        ],
        [
            [],
            [],
            []
        ],
        [
            [null],
            [],
            [null]
        ],
        [
            [1],
            [1 => 1],
            [0 => 1, 1 => 1]
        ],
    ];
  }

  /**
   *
   * @covers Sphp\Tools\Arrays::diff
   * @dataProvider diffData
   * @param array $arr1
   * @param array $arr2
   * @param array $diff
   */
  public function testDiff(array $arr1, array $arr2, array $diff) {
    print_r(Arrays::diff($arr1,$arr2));
    $this->assertEquals(Arrays::diff($arr1,$arr2), $diff);
  }

}
