language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - travis_retry composer install --no-interaction
  - mkdir -p build/logs

script:
  - phpunit --verbose --bootstrap tests/bootstrap.php

sudo: false
