
language: php

php:
  - 7.0
  - 7.1


before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - mkdir -p build/logs

script:
  - phpunit --verbose --coverage-clover build/logs/clover.xml

after_success:
  - php vendor/bin/coveralls -v
  
sudo: false
