language: php

php:
  - 7.4
  
# Cache composer packages
cache:
  directories:
    - $HOME/.composer/cache/files
before_script:
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-en language-pack-fi
  ##- travis_retry composer install --no-interaction
  - composer install
  - mkdir -p build/logs

script:
  - phpunit --verbose --bootstrap sphp/php/tests/bootstrap.php

notifications:
 email: sami.holck@gmail.com