language: php
env:
    global:
        - LANG=fi_Fi.UTF-8
        - LC_ALL=fi_Fi.UTF-8
php:
  - 7.2
  - 7.3
# Cache composer packages
cache:
  directories:
    - $HOME/.composer/cache/files
before_script:
  - travis_retry composer install --no-interaction
  - mkdir -p build/logs

script:
  - phpunit --verbose --bootstrap sphp/php/tests/bootstrap.php

sudo: false
