## YAML Template.
---
Data and Database: 
  default: fas fa-database
  exts:
    csv: fas fa-file-csv
    db:
    dbf:
    mdb:
    sql:
    sqlite:
    sqlite3:
    sqlitedb:
    db-journal:
    db-wal:
    db-shm:
    db3:
    cnf: devicon-mysql-plain
    myd: devicon-mysql-plain
    myi: devicon-mysql-plain
    frm: devicon-mysql-plain
    ibd: devicon-mysql-plain
    mwb: devicon-mysql-plain
Archive files:
  default: far fa-file-archive
  exts:
    zip:
    rar:
    gz:
    tar:
    arj:
    7z:
    deb: devicon-debian-plain-wordmark
    rpm: devicon-redhat-plain-wordmark
    pkg:
    tar.gz:
    z:
    apk:
Apple related:
  default: fab fa-apple
  exts:
    dmg:
    ds_store:
    osx:
    ipsw:
    ipa:
    keychain: 
Android Operation System:
  default: fab fa-android
  exts:
    apk:
    nomedia:
    tdb:
    prop:
    arsc:
    asec:
    sbf:
    ab:
    ap_:
    smali:
    obb:
Windows Operation System:
  default: fab fa-windows
  exts:
    wsf: 
    gadget: 
    lnk: fas fa-link
    bat: fas fa-cogs
    com: fas fa-cogs
    exe: fas fa-cogs
    ini: fas fa-cogs
    dll: fas fa-cogs
    sys: fas fa-cogs
Unix Operation System:
  default: devicon-unix-original
  exts:
    a: 
    conf:
    o: 
    s: 
    sh: 
    so:
    unx:
    uu:
Git version control system: 
  default: fab fa-git
  exts:
    gitignore:
    gitattribute:
    gitkeep:
Programmming Files:
  default: far fa-file-code
  exts:
    js: fab fa-js-square
    json: fab fa-js-square
    php: fab fa-php
    php2: fab fa-php
    php3: fab fa-php
    php4: fab fa-php
    php5: fab fa-php
    phtm: fab fa-php
    phtml: fab fa-php
    phar: fab fa-php
    ctp: devicon-cakephp-plain
    asm: 
    scss: fab fa-sass
    sass: fab fa-sass
    less: fab fa-less
    xhtml:
    md: fab fa-markdown
    markdown: fab fa-markdown
    htm:
    htmls:
    shtml:
    html:
    cer: fas fa-certificate
    css: fab fa-css3-alt
    vb:
    cgi:
    py: fab fa-python
    xml:
    htx:
    rexx:
    asp:
    aspx:
    for:
    ssi:
    sgml:
    tcl:
    ts: devicon-typescript-plain
    tsx: devicon-typescript-plain  
    pl: devicon-perl-plain
    pm: devicon-perl-plain
    c: devicon-c-plain
    h: devicon-c-plain
    cpp: devicon-cplusplus-line
    cxx: devicon-cplusplus-line
    cc: devicon-cplusplus-line
    cs: devicon-csharp-line
    java: fab fa-java
    class: fab fa-java
    jav: fab fa-java
    jar: fab fa-java
    jsp: fab fa-java
    jspx: fab fa-java
    rb: devicon-ruby-plain
    rbw: devicon-ruby-plain
    gem: devicon-ruby-plain
    erb: devicon-ruby-plain
    rjs: devicon-ruby-plain
    rhtml: devicon-ruby-plain
    rdoc: devicon-ruby-plain
Feed Files:
  default: fas fa-rss-square
  exts:
    rss:
    atom:
    atomsvc:
    obi:
Text Files:
  default: far fa-file-alt
  exts:
    mcf:
    pas:
    lst:
    def: 
    txt:
    log:
    list:
    text:
    idc:
    rtx:
    wsc:
    tsv:
    uri:
    uni:
    uris:
    unis:
    abc:
    flx:
    rt:
    wml:
    wmls:
    htt:
    aip:
    htc:
    f90:
    hh:
    lsx:
    m:
    p:
    hlb:
    csh:
    el:
    ksh:
    lsp:
    etx:
    sgm:
    talk:
    spc:
    uil:
    uue:
    vcs:
Video Files:
  default: far fa-file-video
  exts:
    h264:
    afl:
    avs:
    m2v:
    m1v:
    mpe:
    mpa:
    mpg:
    mpeg:
    mp4:
    qt:
    moov:
    mov:
    vdo:
    rv:
    vivo:
    viv:
    vos:
    xdr:
    xsr:
    fmf:
    dl:
    dv:
    dif:
    fli:
    gl:
    isu:
    mjpg:
    mp3:
    mp2:
    asf:
    asx:
    avi:
    qtc:
    scm:
    mv:
    movie:
    vob:
    wmv:
    swf:
    mkv:
    flv:
    3g2:
    3gp:
    m4v:

Images and Photography:
  default: far fa-file-image
  exts:
    ps:
    fif:
    flo:
    svg:
    gif:
    jut:
    nap:
    pic:
    pict:
    jfif:
    jpe:
    jpg:
    jpeg:
    heif:
    png:
    fpx:
    rp:
    wbmp:
    xif:
    ras:
    svf:
    dxf:
    dwg:
    ico:
    art:
    jps:
    nif:
    pcx:
    pct:
    pnm:
    pbm:
    pgm:
    ppm:
    qif:
    qtif:
    qti:
    rgb:
    tif:
    tiff:
    bmp:
    xwd:
    xbm:
    xpm:
audio:
  default: far fa-file-audio
  exts:
    mp3:
    wav:
    ogg:
    wma:
    flac:
    webm:
    it:
    my:
    rmi:
    m2a:
    mpga:
    s3m:
    tsi:
    qcp:
    vox:
    snd:
    aifc:
    aif:
    aiff:
    au:
    jam:
    m3u:
    la:
    ram:
    rm:
    rmm:
    rmp:
    sid:
    ra:
    vqf:
    vql:
    vqe:
    voc:
    wav:
    xm:
Spreadsheet:
  default: far fa-file-excel
  exts:
    xls:
    xlsx:
    xlsm:
    ods:
    fods:
    xlr:
Word Processing:
  default: far fa-file-word
  exts:
    doc:
    dotm:
    dotx:
    docx:
    rtf:
    wps:
    wks:
    odt:
    wpd:
Presentation:
  default: far fa-file-powerpoint
  exts:
    pptx:
    odp:
    pps:
    ppt:
    pptx:
PDF files:
  default: far fa-file-pdf
  exts:
    pdf:
    pdfs:
    pdfxml:
Adobe Photoshop:
  default: devicon-photoshop-plain
  exts:
    psd:
    eps:
Adobe Illustrator:
  default: devicon-illustrator-plain
  exts:
    ai:
    ait:
    line:
Adobe After Effects:
  default: devicon-aftereffects-plain
  exts:
    aep:
    aepx:
    aetx:
    aex:
    ars:
    ffx:
    aecache:
    aegraphic:
    aecap:
Font files:
  default: fas fa-font
  exts:
    fnt:
    fon:
    otf:
    ttf:
