<?php

namespace Sphp\Stdlib;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-12 at 02:27:55.
 */
class FormattableStringsTest extends \PHPUnit_Framework_TestCase {

  /**
   * 
   * @return array
   */
  public function strings() {
    return [
        [""],
        ["foo"],
        ['bar %d %s']
    ];
  }

  /**
   * @covers Sphp\Stdlib\Strings::isEmpty
   * @dataProvider strings
   * @param type $string
   */
  public function testEmpty($string) {
    $s = new FormattableString($string);
    $this->assertSame($string, "$s");
  }

  /**
   * 
   * @return array
   */
  public function stringsAndArgs() {
    return [
        ["", [1,2,3]],
        ["foo", [1,2,3]],
        ['bar %d %s', [1,2,3]],
        ['bar %d %s %s %s', [1,2,3]]
    ];
  }
  /**
   * @covers Sphp\Stdlib\Strings::isEmpty
   * @dataProvider stringsAndArgs
   * @param type $string
   */
  public function testWrongNumberOfArgs(string $string, array $args) {
    
    $s = new FormattableString($string, $args);
    $s->setArguments($args);
    $this->assertSame(vsprintf($string, $args) , "$s");
  }

}
