<?php

namespace Sphp\Util;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-12 at 02:27:55.
 */
class ArraysTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Strings
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		//$this->object = new String("string");
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * Generated from @assert ("abc", "a") == true.
	 *
	 * @covers Sphp\Tools\String::startsWith
	 */
	public function testDiff() {
		$arr1 = ["a" => "a", [1, 3 => 2], 4 => "f"];
		$arr2 = ["a" => "a", [1, 2], 4 => "f"];
		$this->assertEquals(Arrays::diff([], []), []);
		$this->assertEquals(Arrays::diff([1, 2], [2, 1]), []);
		$this->assertEquals(Arrays::diff($arr1, $arr2), [[1, 3 => 2],[1, 2]]);
	}

}
