<?php

namespace Sphp\Util;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-12 at 02:27:55.
 */
class StringsTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Strings
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		//$this->object = new String("string");
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers Sphp\Tools\String::startsWith
	 */
	public function testStartsWith() {
		$this->assertTrue(Strings::startsWith("string", "string"));
		$this->assertTrue(Strings::startsWith("string", ""));
		$this->assertTrue(Strings::startsWith("string", "s"));
		$this->assertFalse(Strings::startsWith("string", "i"));
	}

	/**
	 * @covers Sphp\Tools\String::startsWith
	 */
	public function testEndsWith() {
		$this->assertTrue(Strings::endsWith("string", ["a", "ing", "f"]));
		$this->assertFalse(Strings::endsWith("string", ["a", "d", "f"]));
		$this->assertTrue(Strings::endsWith("string", "ing"));
		$this->assertTrue(Strings::endsWith("string", ""));
		$this->assertTrue(Strings::endsWith("string", "g"));
		$this->assertFalse(Strings::endsWith("string", "i"));
	}

}
