## DB connection
---
sphp_db:
  driver: pdo_mysql
  user: sphp_framework
  password: Vxr79s?8
  host: 192.168.10.208;port=3306
  charset: utf8
  dbname: sphp
  driverOptions: 
    1002: SET NAMES utf8