## Meta data
---
- meta:
    charset: utf-8
- meta:
    http-equiv: X-UA-Compatible
    content: IE=edge
- meta:
    name: viewport
    content: width=device-width, initial-scale=1
- title: SPHPlayground Framework
- meta:
    name: description
    content: SPHPlayground web framework
- meta:
    name: author
    content: Sami Holck
- meta:
    name: keywords
    content: php, scss, css, css3, html, html5, JavaScript, js
- meta:
    name: robots
    content: index, follow
- meta:
    name: mobile-web-app-capable
    content: yes
- meta:
    name: apple-mobile-web-app-capable
    content: yes
- meta:
    http-equiv: Expires
    content: 0
- meta:
    http-equiv: Pragma
    content: no-cache
- meta:
    http-equiv: Cache-Control
    content: no-cache
- meta:
    http-equiv: imagetoolbar
    content: no
- meta:
    http-equiv: x-dns-prefetch-control
    content: off
- meta:
    http-equiv: apple-mobile-web-app-capable
    content: yes
- link:
    rel: apple-touch-icon
    sizes: 180x180
    href: "/apple-touch-icon.png"
- link: 
    rel: icon
    type: image/png
    sizes: 32x32
    href: "/favicon-32x32.png"
- link: 
    rel: icon
    type: "image/png" 
    sizes: 16x16
    href: "/favicon-16x16.png"
- link: 
    rel: manifest
    href: '/site.webmanifest'
- link: 
    rel: mask-icon
    href: '/safari-pinned-tab.svg'
    color: '#555555'
- meta:
    name: msapplication-TileColor
    content: '#edd4cd'
- meta:
    name: msapplication-TileImage
    content: '/mstile-144x144.png'
- meta:
    name: theme-color
    content: '#ffffff'
